version: "3"
services:
  debug:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "127.0.0.1:2345:2345"
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./app"